# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           none
relative_permalinks: true

# Setup
title:               Tiago de Souza
tagline:             Blog pessoal sobre tecnologia da informação
url:                 http://blog.tiagosr.com
paginate:            3
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Tiago de Souza
  url:               http://blog.tiagosr.com
  email:             tsr@tiagosr.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/tsouzar/tsouzar.github.io
