title: Tiago de Souza
description: Blog pessoal onde abordo questões de programação, telecomunicações e talvez algo mais.

url: http://blog.tiagosr.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 1

navigation:
 - title: Home
   url: /index.html

social:
   github: tsouzar
   facebook: TiagoSRibeiro
   email: tsr@tiagosr.com
