title: Tiago de Souza
description: Blog pessoal onde abordo questões de programação, telecomunicações e talvez algo mais.

url: http://blog.tiagosr.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 1

navigation:
 - title: Home
   url: /index.html
# - title: About
#   url: /about
# - title: Contact
#   url: /contact

social:
   github: tsouzar
#   twitter: brianmaierjr
   facebook: TiagoSRibeiro
   email: tsr@tiagosr.com

#google_analytics: "UA-58263416-1"
