title: Tiago de Souza
description: Blog pessoal onde abordo questões de programação, telecomunicações e talvez algo mais.

url: http://blog.tiagosr.com
baseurl: ""
paginate_path: "page:num/"
permalink: :title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Início
   url: /index.html

social:
   github: tsouzar
   facebook: TiagoSRibeiro
   email: tsr@tiagosr.com
